language: php
php:
  - 7.0
  - 7.1
  - 7.2
before_script:
  - composer self-update
  - composer install --dev --no-interaction
script:
  - composer test
after_success:
  - travis_retry php vendor/bin/coveralls -v
